#!/usr/bin/env python3
# gen_t34.py - embed the user-supplied T-34 GLB into src/t34_data.c (GT34).
# Source is a Z-up / Y-forward DCC export in arbitrary units. We bake into the
# game vehicle convention: nose toward -Z, up +Y, right +X, ground at y=0,
# metres, centred on the hull so it rotates about its middle.
import json, struct, io, os
import numpy as np
from PIL import Image

ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GLB="/tmp/t34/87557340/glbfile.glb"
OUT=os.path.join(ROOT,"src","t34_data.c")

# tunable calibration constants (iterated against engine screenshots)
SCALE   = float(os.environ.get("T34_SCALE","0.0264"))  # source units -> metres
FLIPF   = os.environ.get("T34_FLIP","1")=="1"          # swap nose end
TSIZE   = 512

d=open(GLB,"rb").read(); off=12; chunks=[]
while off<len(d):
    L,T=struct.unpack("<II",d[off:off+8]); off+=8; chunks.append((T,d[off:off+L])); off+=L
j=json.loads(chunks[0][1]); B=chunks[1][1]
bvs=j["bufferViews"]; accs=j["accessors"]
DT={5120:np.int8,5121:np.uint8,5122:np.int16,5123:np.uint16,5125:np.uint32,5126:np.float32}
NC={"SCALAR":1,"VEC2":2,"VEC3":3,"VEC4":4}
def readacc(ai):
    a=accs[ai]; bv=bvs[a["bufferView"]]
    o=bv.get("byteOffset",0)+a.get("byteOffset",0)
    dt=np.dtype(DT[a["componentType"]]).newbyteorder("<")
    return np.frombuffer(B,dt,count=a["count"]*NC[a["type"]],offset=o).reshape(a["count"],NC[a["type"]])

def emit_f32(name, arr, per=6, prec=5):
    flat=np.asarray(arr,dtype=np.float64).reshape(-1); lines=[]
    for i in range(0,flat.size,per):
        lines.append(",".join("%.*g"%(prec,x) for x in flat[i:i+per]))
    return "static const float %s[]={\n%s};\n"%(name,",\n".join(lines))
def emit_u16(name, arr, per=12):
    flat=np.asarray(arr,dtype=np.uint16).reshape(-1)
    lines=[",".join(str(int(x)) for x in flat[i:i+per]) for i in range(0,flat.size,per)]
    return "static const unsigned short %s[]={\n%s};\n"%(name,",\n".join(lines))
def emit_bytes(name, data, per=24):
    lines=[",".join(str(b) for b in data[i:i+per]) for i in range(0,len(data),per)]
    return "static const unsigned char %s[]={\n%s};\n"%(name,",\n".join(lines))

# ---- the three base-color textures: material RELS->img0, TOWER->img3, BODY->img6
MAT_IMG={"RELS":0,"TOWER":3,"BODY":6}
texbytes=[]; texname=[]
for key in ("RELS","TOWER","BODY"):
    ii=MAT_IMG[key]; immeta=j["images"][ii]
    ibv=bvs[immeta["bufferView"]]; ioff=ibv.get("byteOffset",0); ilen=ibv["byteLength"]
    img=Image.open(io.BytesIO(B[ioff:ioff+ilen])).convert("RGB")
    img=img.resize((TSIZE,TSIZE),Image.LANCZOS)
    buf=io.BytesIO(); img.save(buf,"JPEG",quality=84,optimize=True)
    texbytes.append(buf.getvalue()); texname.append("GT34_T%d"%len(texbytes))
    print(key,"jpeg",len(texbytes[-1]),"bytes")

# gather global source frame from the hull (body) mesh for a clean ground/centre
bodypos=readacc(j["meshes"][2]["primitives"][0]["attributes"]["POSITION"])
midX=(bodypos[:,0].min()+bodypos[:,0].max())*0.5
midY=(bodypos[:,1].min()+bodypos[:,1].max())*0.5
minZ=bodypos[:,2].min()
print("hull midX",midX,"midY",midY,"minZ",minZ)

def mattex(name):
    n=name.upper()
    if "BODY" in n: return 2
    if "TOWER" in n: return 1
    return 0  # tracks

subs=[]
for mi,m in enumerate(j["meshes"]):
    if mi==3:
        # mesh 3 "Rels001_RELS_0" is a stray, UV-broken duplicate in the source
        # export: it stretches ~14.7 m (vs the 6 m hull), sinks below ground and
        # samples the texture border to white. The hull + tower + the other track
        # run already render both track runs correctly, so drop it.
        print("skip stray mesh3",m["name"]); continue
    pr=m["primitives"][0]; att=pr["attributes"]
    pos=readacc(att["POSITION"]).astype(np.float64)
    nrm=readacc(att["NORMAL"]).astype(np.float64)
    uv =readacc(att["TEXCOORD_0"]).astype(np.float64)
    idx=readacc(pr["indices"]).reshape(-1).astype(np.uint32)
    sgn=-1.0 if FLIPF else 1.0
    # world: X <- src X (width), Y <- src Z (up), Z <- src Y (length, nose -Z)
    P=np.empty_like(pos)
    P[:,0]=(pos[:,0]-midX)*SCALE
    P[:,1]=(pos[:,2]-minZ)*SCALE
    P[:,2]=sgn*(pos[:,1]-midY)*SCALE
    N=np.empty_like(nrm)
    N[:,0]= nrm[:,0]
    N[:,1]= nrm[:,2]
    N[:,2]= sgn*nrm[:,1]
    nl=np.linalg.norm(N,axis=1,keepdims=True); nl[nl==0]=1; N=N/nl
    assert P.shape[0]<65536, m["name"]
    subs.append((m["name"],P,N,uv,idx.astype(np.uint16),mattex(m["name"])))
    print("sub",mi,m["name"],"tex",mattex(m["name"]),"verts",P.shape[0],"tris",idx.size//3,
          "bbox y",P[:,1].min().round(2),P[:,1].max().round(2),
          "z",P[:,2].min().round(2),P[:,2].max().round(2),
          "x",P[:,0].min().round(2),P[:,0].max().round(2))

with open(OUT,"w") as f:
    f.write('// Auto-generated by tools/gen_t34.py from the user-supplied T-34 GLB.\n')
    f.write('// Vehicle local space: nose -Z, up +Y, metres, ground at y=0.\n')
    f.write('#include "guns_data.h"\n\n')
    for nm,db in zip(texname,texbytes): f.write(emit_bytes(nm,db))
    f.write("static const unsigned char* const GT34_TEX[3]={%s};\n"%",".join(texname))
    f.write("static const int GT34_TEXLEN[3]={%s};\n\n"%",".join(str(len(b)) for b in texbytes))
    rows=[]
    for si,(name,P,N,U,I,ti) in enumerate(subs):
        f.write(emit_f32("GT34_S%d_P"%si,P))
        f.write(emit_f32("GT34_S%d_N"%si,N,prec=4))
        f.write(emit_f32("GT34_S%d_U"%si,U,prec=5))
        f.write(emit_u16("GT34_S%d_I16"%si,I))
        rows.append("{%d,%d,0,%d,GT34_S%d_P,GT34_S%d_N,GT34_S%d_U,GT34_S%d_I16,0}"
                    %(P.shape[0],I.size,ti,si,si,si,si))
    f.write("static const GSubData GT34_SUBS[]={%s};\n"%",".join(rows))
    f.write("const GGunData GT34={%d,3,GT34_SUBS,GT34_TEX,GT34_TEXLEN};\n"%len(subs))
print("wrote",OUT,os.path.getsize(OUT),"bytes")
